package ph.com.lllc.enums;

public enum EmployeePosition {
    SUPER_ADMIN,
    IT_ADMINISTRATOR,
    CHIEF_OPERATING_OFFICER,
    HUMAN_RESOURCE_MANAGER,
    CASE_MANAGER,
    SENIOR_BEHAVIORAL_THERAPIST,
    BEHAVIORAL_THERAPIST,
    SECRETARY,
    ACCOUNTING_OFFICER,
    MAINTENANCE_STAFF,

    PSYCHOLOGIST,
    SPEECH_LANGUAGE_PATHOLOGIST,
    OCCUPATIONAL_THERAPIST
}
