# =============================
# Server Configuration
# =============================
server.port=8080
server.address=192.168.1.100
spring.application.name=little-leaps-learning-center-service

# =============================
# Spring JPA / Hibernate
# =============================
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.jdbc.time_zone=GMT+8
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# =============================
# Create Schema
# =============================
spring.datasource.db.schema=little_leap_learning_center_db
spring.datasource.db.queryForObject=SELECT nextval('%s')

# =============================
# DataSource (Postgres) + HikariCP
# =============================
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/lllc_db?currentSchema=little_leap_learning_center_db
spring.jpa.properties.hibernate.default_schema=little_leap_learning_center_db
spring.datasource.username=postgres
spring.datasource.password=password

# =============================
# HikariCP settings
# =============================
spring.datasource.hikari.pool-name=HikariPool
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.auto-commit=false
spring.datasource.hikari.leak-detection-threshold=20000

spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.max-lifetime=600000

# =============================
# Security / Paths
# =============================
security.permit.paths.lllc.swaggerPath=/v3/api-docs/**,/swagger-ui/**,/swagger-ui.html
security.permit.paths.lllc.staticPath=/css/**,/js/**,/img/**,/fonts/**,/webjars/**,/common/**,/custom/**
security.permit.paths.lllc.internalPath=/api/v1/**
security.permit.paths.lllc.defaultPath=/lllc/**

security.permit.paths.lllc.clientPath=/lllc/client/**
security.permit.paths.lllc.clientLogin=/lllc/client/login
security.permit.paths.lllc.clientLogout=/lllc/client/logout
security.permit.paths.lllc.clientDashboard=/lllc/client/dashboard

security.permit.paths.lllc.staffPath=/lllc/staff/**
security.permit.paths.lllc.staffLogin=/lllc/staff/login
security.permit.paths.lllc.staffLogout=/lllc/staff/logout
security.permit.paths.lllc.staffDashboard=/lllc/staff/dashboard

# =============================
# Redis API
# =============================
upstash.redis.url=https://one-hawk-110033.upstash.io
upstash.redis.token=gQAAAAAAAa3RAAIgcDE1MzcxZGY0NTE4ZmE0NTllYTVkNTY4NjE1MTYwOWY1Ng
